cache: bundler
language: ruby
rvm:
  - 2.5.3
install: gem install bundler --no-rdoc --no-ri
script:
  - bundle install
  - bundle exec jekyll build
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
notifications:
  email: false
