title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "twitter_username:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - english.md
 - language.md
 - mathematics.md
 - reading.md
 - writing.md

sorted_domains:
  english:
    - "Receptive Modalities"
    - "Interactive Modalities"
    - "Productive Modalities"
    - "ELA Language"
  language:
    - "Conventions of Standard English"
    - "Knowledge of Language"
    - "Vocabulary Acquisition and Use"
  mathematics:
    - "Mathematical Practice"
    - "Operations and Algebraic Thinking"
    - "Number and Operations: Base Ten"
    - "Number and Operations: Fractions"
    - "Measurement and Data"
    - "Geometry"
    - "Ratios and Proportional Relationships"
    - "The Number System"
    - "Expressions and Equations"
    - "Functions"
    - "Statistics and Probability"
  reading:
    - "Key Ideas and Details"
    - "Craft and Structure"
    - "Integration of Knowledge"
    - "Range of Reading and Level of Text Complexity"
  writing:
    - "Text Types and Purposes"
    - "Production and Distribution of Writing"
    - "Research to Build and Present Knowledge"

# Build settings
# theme: minima

permalink: pretty

# sass:
#   sass_dir: _sass

plugins:
 - jekyll-feed
 - jekyll-seo-tag

collections_dir: collections

collections:
  english:
    output: true
  language:
    output: true
  mathematics:
    output: true
  reading:
    output: true
  writing:
    output: true
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: index1
  - scope:
      path: ""
      type: "english"
    values:
      layout: default
  - scope:
      path: ""
      type: "language"
    values:
      layout: default
  - scope:
      path: ""
      type: "mathematics"
    values:
      layout: default
  - scope:
      path: "_mathematics/Content"
      type: "mathematics"
    values:
      layout: default2
  - scope:
      path: ""
      type: "reading"
    values:
      layout: default
  - scope:
      path: ""
      type: "writing"
    values:
      layout: default
